################################################################################
# ==> Tasks for install Oracle Fussion Middleware Infrastructure software 12c R2
# ==> to an Oracle Linux 7.1 system. Supports version 12.2.1
# ==> author: Christos Vezalis
################################################################################

# ==> Install Fussion Middleware Infrastructure Software
- name: Create installer directory
  file: state=directory path={{ mw_installer_folder }}
- name: Copy Middleware Installer
  copy: src={{ mw_installer }} dest={{ mw_installer_folder }}
- name: Copy file for silent installation
  template: src=silent-weblogic.txt dest={{ mw_installer_folder }}
- name: Copy OraInst.loc
  template: src=oraInst.loc dest={{ mw_installer_folder }}
- name: execute Weblogic installer
  command: "{{ jdk_folder }}/bin/java -Xms1024m -Xmx1024m -jar {{ mw_installer_folder }}/{{ mw_installer }} -silent -responseFile {{ mw_installer_folder }}/silent-weblogic.txt -invPtrLoc {{ mw_installer_folder }}/oraInst.loc"
